- include/client.h
- include/options.h
Basic design is: 
* Mixer client only provides cache and aggregation functions. 
* Transport is separated out from this client so different platforms can use this client with their different transports.
* Client interface is exactly the same as transport interface; easier to integrate.
Please help to review this interface.
> Define interface for client.

- BUILD
- utils/google_macros.h
- utils/simple_lru_cache.h
- utils/simple_lru_cache_inl.h
- utils/simple_lru_cache_test.cc
Borrowed from Service-control-client, will be used for Check cache.
> Add simple lru cache into utils.

- BUILD
- include/client.h
- src/client_impl.cc
- src/client_impl.h
- src/client_impl_test.cc
- src/stream_transport.h
- src/stream_transport_test.cc
* Renamed file src/transport_impl.h  to src/stream_transport.h
* Moved most test cases from client_impl_test to stream_transport_test.
> Remove protobuf based entry calls.

- BUILD
- src/signature.cc
- src/signature.h
- src/signature_test.cc
- utils/md5.cc
- utils/md5.h
- utils/md5_test.cc
Signature will be used for cache.
> Generate signature for Attributes.

- .bazelrc
- .travis.yml
- src/check_cache.cc
- src/signature_test.cc
- src/stream_transport.h
- src/transport.h
Some other small changes:
* add .bazelrc file
* replace unique_lock with lock_guard
* rename a variable attributes_map_ to attributes in src/signature_test.cc
* Fixed a bug in signature_test.cc: AddTime() did not set type.
> Added tsan and asan test in travis test.

- BUILD
- include/attribute.h
- include/client.h
- src/attribute.cc
- src/attribute_context.cc
- src/attribute_context.h
- src/client_impl.cc
Also moved the Attributes struct related code into its own files.
> Support attribute context update.

- BUILD
- include/attribute.h
- src/attribute.cc
- src/attribute_context.cc
- src/attribute_context.h
- src/attribute_context_test.cc
- src/attribute_test.cc
- src/context_update.cc
- src/context_update.h
- src/context_update_test.cc
- src/signature_test.cc
* split AttributeContext::Context into ContextUpdate, move it into its own files
* write unit_tests:  attirbute_test.cc, attribte_context_test.cc and context_update_test.cc
> Add more unit_tests.

- BUILD
- utils/circular_queue.h
- utils/circular_queue_test.cc
- utils/time_based_counter.cc
- utils/time_based_counter.h
- utils/time_based_counter_test.cc
This is in preparation to implement quota prefetch algorithm described in
https://github.com/qiwzhang/rate-limit-prefetch
> Add circular_queue and time_based_counter classes.

- src/cache_key_set.cc
- src/cache_key_set.h
- src/cache_key_set_test.cc
- src/check_cache.cc
- src/check_cache.h
- src/signature_test.cc
To allow creating "Inclusive", "Exclusive" and "All" key set.
Header file only has interface.   All implementation are in cc file.
> Refactory CacheKeySet class.

- BUILD
- include/client.h
- include/options.h
- prefetch/quota_prefetch.cc
- prefetch/quota_prefetch.h
- src/attribute_context.cc
- src/client_impl.cc
- src/client_impl_test.cc
- utils/protobuf.cc
- utils/protobuf.h
Piggy bag some other minor changes
1) quota_prefetch to use -1 granted amount to indicate network failure.
2) removed ReportOptions 
3) changed QuotaOptions.
> Move protobuf conversion code to utils.

- BUILD
- include/client.h
- include/timer.h
Just an interface for callers to provide a function to create timer
> Add timer for batching reports.

- BUILD
- create_global_dictionary.py
- repositories.bzl
- src/attribute_converter.cc
- src/attribute_converter.h
- src/attribute_converter_test.cc
- src/client_impl.cc
- src/global_dictionary.h
- src/quota_cache.cc
word header file is auto generated from yaml file.
Also set global_word_count field
> use global dictionary.

- src/attribute_converter.cc
- src/attribute_converter.h
- src/client_impl.cc
- src/report_batch.cc
- src/report_batch.h
- utils/protobuf.cc
- utils/protobuf.h
If there is any dictionary related error, shrink global dictionary back to the first version.
> global dictionary fall back.

- repositories.bzl
- src/attribute_converter_test.cc
- src/global_dictionary.cc
Reverts istio/mixerclient#90 temprorarily to unblock istio/proxy#398
> Revert "update global dictionary to 124."

- BUILD
- WORKSPACE
- istio.deps
- repositories.bzl
This reverts commit 506d9c1113ecfe3bbffd5d5f55968a15282119a1.
> Revert "Fix for API build (#166)"

- script/check-license-headers
It is OK to have more than 1 lines of copyright.
> fix check-license-headers

- prow/mixerclient-presubmit.sh
This PR allows for us to switch to prow for gating PR
> add prow presubmit

- control/src/http/request_handler_impl_test.cc
- control/src/http/service_context.h
- repositories.bzl
> use disable_check_calls in service config

- src/referenced.h
> Fix compile with clang/llvm-c++

- control/src/mock_mixer_client.h
- include/client.h
- src/client_impl.cc
- src/client_impl.h
- src/client_impl_test.cc
- src/report_batch.cc
- src/report_batch.h
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #132 
```release-note
Provide statistics for mixer client.
```
> Provide stats for mixer client.

- prow/mixerclient-presubmit.sh
- tools/bazel.rc
Add tsan test for presubmit
```release-note
None
```
> add tsan test.

- control/src/attribute_names.cc
- control/src/attribute_names.h
- control/src/http/attributes_builder.cc
- control/src/tcp/attributes_builder.cc
- control/src/tcp/attributes_builder_test.cc
Set check.error_code and message attributes.
```release-note
None
```
> Set check error code and message.

- istio.deps
- repositories.bzl
This PR will be merged automatically once checks are successful.
```release-note
none
```
> [DO NOT MERGE] Auto PR to update dependencies of mixerclient

- control/include/http/report_data.h
- control/src/http/attributes_builder.cc
- control/src/http/attributes_builder_test.cc
- control/src/http/mock_report_data.h
> Don't send attributes destination.ip and destination.port from HTTP filter.

- control/include/http/controller.h
- control/src/http/client_context.cc
- control/src/http/client_context.h
- control/src/http/controller_impl.cc
- control/src/http/request_handler_impl.cc
- control/src/http/request_handler_impl_test.cc
Clean up legacy config code
```release-note
None
```
> Clean legacy config
