istio/mixerclient

include/client.h
src/client_impl.cc
src/client_impl.h

The full set of attributes will be used between proxy and mixer_client.  Mixer_client will use attribute context (within a gRPC stream) to generate attribute_update before calling Mixer.
The current calls using protobuf messages will be removed.

Support attributes in the interface.

---

include/transport.h
src/grpc_transport.cc
src/stream_transport.h

Use shared_ptr for Writer interface so it can pass a ref_count to ReaderThread.

Fix crash when mixer server is killed.

---

src/transport.h

stream.Call has two steps:  FillProto with attribute context, and gRPC.Write.  
FillingProto and gRPC.Write() are individually protected. But two steps should be done atomically.  Otherwise, following may happen:  FillProto 1 with ctx,  write did not happen, then FillProto 2 whose context is based on 1,  then 2 Write to grpc first. then write 1.
This change will make sure stream.Call is sync.  its two steps are done atomically

Sync up the stream.Call

---

include/attribute.h
src/attribute.cc
src/transport.h

Use two special attributes "quota.name" and "quota.amount" to pass info to protobuf QuotaRequest.

Support FillProto for QuotaRequest.

---

BUILD
include/options.h
src/cache_key_set.cc
src/cache_key_set.h
src/cache_key_set_test.cc
src/check_cache.cc
src/check_cache.h
src/signature.cc
src/signature.h
src/signature_test.cc

If a cache key is "request.headers/:method".  It means only to use the string map attribute "request.headers" and its ":method" key.  
If a cache key is "source.labels",  it means to use all values in "source.labels" string map attribute.

Support cache key for partial string map value

---

src/client_impl.cc
utils/protobuf.cc
utils/protobuf.h

rpc.status used to be both network status and server status.  Now response body added status, it is for server status.   rpc.status is for network status. 
Client need to use response.status and convert it for the check request.

Use check response status.

---

BUILD
create_global_dictionary.py
src/global_dictionary.cc

It requires all testing env (travis, and jenkins) to have python yaml package installed.
It is too much trouble to install it for all test env. 
Each time, we just run the python script manually, and check in generated cc file.

Not to use bazel to generate global_dictionary.cc file

---

create_global_dictionary.py
src/global_dictionary.cc

MIxer python global dictionary conversion code did not use "yaml" package.  Instead it is just checking "-" prefix.  
https://github.com/istio/mixer/blob/master/bin/generate_word_list.py
If python yaml is used, 200 has to be wrapped with single quote as '200' so it will be loaded as string instead of int.
Since mixer converter did not use yaml loading,  mixer dictionary is using '200' with single quota. 
To be consistent,   mixerclient should not use yaml loading too. Instead of changing mixer, it is easier to change client.

Use mixer python code to convert global dictionary.

---

src/attribute_converter.cc
src/attribute_converter.h

Shrink() could be called parallel.  But adding a mutex to protect the map is expensive since it is called so often.   Shrink should be rare events and only happen once.  
Adding a top_index and just update the top_index for shrink is the alternative.

Use top_index to implement global dictionary shrink.

---

src/check_cache.cc
src/quota_cache.cc
src/referenced.cc
src/referenced.h
src/referenced_test.cc

Multiple quota metrics are sharing the same cache.  Cache key should include quota name otherwise they may collide.

Quota cache key should include quota name.

---

api_spec/BUILD
api_spec/src/http_template.cc
api_spec/src/http_template.h
api_spec/src/http_template_test.cc
api_spec/src/path_matcher.h
api_spec/src/path_matcher_node.cc
api_spec/src/path_matcher_node.h
api_spec/src/path_matcher_test.cc

These code are copied from ESP (https://github.com/cloudendpoints/esp).  It will be used for template match for http api_spec.
Following libraries will be at top level folder:
api_spec/
auth/
mixer_client/
mixer_control/
Such that api_spec and auth libraries can be used by mixer_control.   Or someone can build a simple Envoy filter to call them directly.

Copy path matcher code over for api_spec.

---

quota/BUILD
quota/include/config_parser.h
quota/include/requirement.h
quota/src/config_parser_impl.cc
quota/src/config_parser_impl.h
quota/src/config_parser_impl_test.cc

Just moved the code from istio/proxy:src/envoy/mixer to istio/mixerclient
* Changed the namespace.  
* Added a map to re-load std::regex objects for optimization.
The reason that the include/requirement.h is in its own header library is because this header file may be used by mixerclient/client.h directly  to pass quota requirement to quota cache code.

Add quota config parser.

---

BUILD
control/include/http/controller.h
control/src/client_context_base.cc
control/src/client_context_base.h
control/src/http/client_context.h
control/src/http/request_handler_impl.cc
control/src/http/request_handler_impl_test.cc
control/src/mock_mixer_client.h
control/src/tcp/request_handler_impl.cc
control/src/tcp/request_handler_impl_test.cc
include/client.h
src/client_impl.cc
src/client_impl.h
src/client_impl_test.cc
src/quota_cache.cc
src/quota_cache.h
src/quota_cache_test.cc

It used to be in the attributes,  used hardcoded  "quota.name" and "quota.amount" attributes to only pass one requirement. 
Now changed to use vector to pass quota requirement in the Check call to client.

Separate quota requirements from attributes.

---

include/timer.h

fails to compile on ubuntu 17.10
g++ (Ubuntu 7.2.0-8ubuntu3) 7.2.0
because of undefined std::function. adding the header fixes this.

fix compilation with g++ 7.2.0

---

control/include/http/controller.h
control/src/BUILD
control/src/client_context_base.cc
control/src/client_context_base.h
control/src/http/BUILD
control/src/http/client_context.cc
control/src/http/client_context.h
control/src/http/controller_impl.cc
control/src/http/controller_impl.h
control/src/http/request_handler_impl.cc
control/src/http/request_handler_impl_test.cc
control/src/http/service_context.cc
control/src/http/service_context.h
control/src/request_context.h
control/src/tcp/client_context.h
control/src/tcp/request_handler_impl.cc
control/src/tcp/request_handler_impl_test.cc
quota/include/config_parser.h
quota/src/config_parser_impl.cc
quota/src/config_parser_impl.h
quota/src/config_parser_impl_test.cc

* Use RequestContext to store quota vector
* Add cache map for ServiceContext so it can be used to preprocess config data.
* Change quota ConfigParser GetRequirements() function to not to return quota vector, instead pass its raw pointer as last argument so the data can be appended.

Integrate with quota parser

---

control/src/http/client_context.cc
control/src/http/client_context.h
control/src/http/controller_impl.cc
control/src/http/request_handler_impl_test.cc
control/src/http/service_context.cc
control/src/http/service_context.h

If a mixer filter is only used for forwarding attributes,  it may not have service_configs map.
```release-note
NONE
```

Support empty service_configs.

---

src/check_cache.cc
src/quota_cache.cc
src/referenced.cc
src/referenced.h
src/referenced_test.cc

1. Add map_key caching support for string maps
2. Refactor decode into common code.
3. Introduce AttributeRef for name and map_key

Add map_key caching support for string maps

---

control/src/http/service_context.cc
control/src/http/service_context.h

service config should be stored in service_context.  Should not use the pointer since the object life time could not be controlled. 
```release-note
NONE
```

Fixed a test failure issue.

---

control/include/http/check_data.h
control/src/attribute_names.cc
control/src/attribute_names.h
control/src/http/attributes_builder.cc
control/src/http/attributes_builder.h
control/src/http/attributes_builder_test.cc
control/src/http/mock_check_data.h

**What this PR does / why we need it**: Extracts information from "sec-istio-auth-userinfo" header which is generated from auth filter, and generates authentication attributes for mixer server to check. This is part of efforts that enable auth filter in envoy.
```release-note
None
```

Support mixerclient to generate authentication attributes

---

control/include/http/check_data.h
control/include/http/request_handler.h
control/src/http/attributes_builder.cc
control/src/http/attributes_builder.h
control/src/http/attributes_builder_test.cc
control/src/http/mock_check_data.h
control/src/http/request_handler_impl.cc
control/src/http/request_handler_impl.h
control/src/http/request_handler_impl_test.cc

To support sending Report for requests rejected by other filters, such as auth and fault injections.
1) add a new method ExtractRequestAttributes()
2) split CheckData interface into two: one is mutable, another is non-mutable.  Check() will take both interfaces, but ExtractRequestAttribute() only take non-mutable since its header_map could not be changed.
```release-note
None
```

Auth report

---

src/attributes_builder.cc

Don't try to convert empty IP string to bytes.  Just send it as empty bytes.
```release-note
None
```

Not to log warning when converting empty ip attributes

---

control/src/http/attributes_builder.cc

Ensures that http status code is reported regardless of whether it was a result of a check failure or came from the back end.
**Which issue this PR fixes** 
Fixes issue when 429 response was received by the client, but "report" call omitted `response.code`. This results in inconsistent metrics reporting and hence failed mixer e2e test.

Report http status code, regardless of check result

---

BUILD
WORKSPACE
cc_gogo_protobuf.bzl
googleapis.bzl
protobuf.bzl
repositories.bzl
x_tools_imports.bzl

* istio/api repo removed all bazel bzl files used by mixerclient and proxy.
* Move these files into this repo
```release-note
None
```

Add Bazel bzl files from api.

---

control/include/http/controller.h
control/src/http/client_context.cc
control/src/http/client_context.h
control/src/http/controller_impl.cc
control/src/http/controller_impl.h
control/src/http/request_handler_impl_test.cc

To support dynamic service config change.
service config is coming from Envoy per-route in RDS.  It can be changed overtime without re-contructing mixer fitter or mixer client control object.   
Add a LRU cache to store these known service config.
```release-note
None
```

Add LRU cache for service config.

---

control/include/http/check_data.h
control/include/http/report_data.h
control/include/tcp/check_data.h
control/include/tcp/report_data.h
control/src/attribute_names.cc
control/src/attribute_names.h
control/src/http/attributes_builder.cc
control/src/http/attributes_builder_test.cc
control/src/http/mock_check_data.h
control/src/http/mock_report_data.h
control/src/tcp/attributes_builder.cc
control/src/tcp/attributes_builder_test.cc
control/src/tcp/mock_check_data.h

**What this PR does / why we need it**: Introduce new mixer attribute "connection.mtls" which indicates whether connection is mutual TLS enabled. Add virtual function bool IsMutualTlsEnabledConnection() into http/check_data.h and tcp/check_data.h, and call this function inside AttributesBuilder::ExtractCheckAttributes(). Add another virtual function bool GetDestinationIpPort(std::string* ip, int* port) to report destination IP and port from HTTP filter.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #426 
```release-note
```

Introduce new attribute connection.mtls
